// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace SmartV;


public delegate void VectorFunc0 <T>(Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc1 <T>(VectorFuncArg<T> arg1, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc2 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc3 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc4 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc5 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc6 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc7 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc8 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc9 <T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc10<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc11<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc12<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, VectorFuncArg<T> arg12, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc13<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, VectorFuncArg<T> arg12, VectorFuncArg<T> arg13, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc14<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, VectorFuncArg<T> arg12, VectorFuncArg<T> arg13, VectorFuncArg<T> arg14, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc15<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, VectorFuncArg<T> arg12, VectorFuncArg<T> arg13, VectorFuncArg<T> arg14, VectorFuncArg<T> arg15, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}


public delegate void VectorFunc16<T>(VectorFuncArg<T> arg1, VectorFuncArg<T> arg2, VectorFuncArg<T> arg3, VectorFuncArg<T> arg4, VectorFuncArg<T> arg5, VectorFuncArg<T> arg6, VectorFuncArg<T> arg7, VectorFuncArg<T> arg8, VectorFuncArg<T> arg9, VectorFuncArg<T> arg10, VectorFuncArg<T> arg11, VectorFuncArg<T> arg12, VectorFuncArg<T> arg13, VectorFuncArg<T> arg14, VectorFuncArg<T> arg15, VectorFuncArg<T> arg16, Span<T> ans) where T : unmanaged;
partial interface IVectorOperation<T> where T : unmanaged
{
}
partial class VectorOperation
{
    partial class _Default
    {
    }

    partial class _Parallelized
    {
    }
}

